"""
Industry-specific context injected into every EA agent prompt.
Each entry shapes scoring thresholds, compliance requirements, tech benchmarks,
and recommendation language to match real market conditions for that sector.
"""

INDUSTRY_CONTEXT = {
    "Financial Services": {
        "display": "Financial Services",
        "sub_sectors": ["Banking", "Insurance", "Capital Markets", "Payments & FinTech"],
        "compliance": ["PCI-DSS", "SOX", "Basel III/IV", "GDPR", "MiFID II", "DORA", "BCBS 239", "IFRS 9"],
        "key_concerns": [
            "Regulatory reporting accuracy and audit trails",
            "Real-time fraud detection and AML",
            "Open banking / API-first architecture",
            "Core banking modernisation (legacy mainframe replacement)",
            "Cyber resilience and operational continuity under DORA",
            "Data sovereignty and cross-border data flows",
        ],
        "tech_trends": [
            "Cloud-native core banking (Temenos, Thought Machine, Mambu)",
            "AI/ML for credit risk, fraud, and customer propensity",
            "Zero-trust security architecture",
            "Real-time payment rails (ISO 20022 migration)",
            "Event-driven microservices replacing monolithic systems",
        ],
        "critical_app_categories": ["Core Banking", "Payment Processing", "Risk Management", "Regulatory Reporting", "Trading Platforms"],
        "maturity_benchmark": "Financial institutions are expected to operate at EA Maturity Level 3-4 due to heavy regulatory pressure and significant IT investment. Anything below Level 3 is a regulatory risk.",
        "cost_benchmark": "Financial services firms typically spend 8-12% of revenue on IT. Legacy mainframe TCO is 3-5x equivalent cloud-native alternatives.",
        "elimination_guidance": "Prioritise legacy COBOL/mainframe apps, shadow IT reporting tools, and duplicate CRM/ERP instances. Compliance-critical apps must have certified replacements before elimination.",
        "risk_amplifiers": ["Single points of failure in payment processing are CRITICAL", "Any app touching customer financial data requires encryption-at-rest audit", "Regulatory reporting systems cannot be eliminated without regulator notification"],
        "market_context": "2024-2025: Financial services sector under intense regulatory scrutiny (DORA effective Jan 2025). Cloud adoption accelerating but legacy core banking remains the #1 technical debt issue. AI/ML investment highest of any sector.",
    },

    "Healthcare": {
        "display": "Healthcare & Life Sciences",
        "sub_sectors": ["Hospitals & Health Systems", "Pharmaceuticals", "Medical Devices / MedTech", "Health Insurance / Payer"],
        "compliance": ["HIPAA", "HITECH", "FDA 21 CFR Part 11", "MDR (EU)", "HL7 FHIR", "ICD-10/11", "SOC 2 Type II"],
        "key_concerns": [
            "Patient data privacy and HIPAA breach prevention",
            "Clinical system uptime (EHR/EMR availability is patient-safety critical)",
            "Interoperability across care settings (FHIR APIs, care coordination)",
            "Medical device software security and FDA validation",
            "AI/ML clinical decision support governance",
            "Supply chain visibility for pharmaceuticals",
        ],
        "tech_trends": [
            "Cloud EHR migration (Epic on AWS, Oracle Health)",
            "FHIR-based interoperability platforms",
            "AI diagnostics and clinical decision support",
            "Remote patient monitoring / IoMT",
            "Genomics data platforms and precision medicine",
        ],
        "critical_app_categories": ["EHR/EMR", "Clinical Decision Support", "Medical Imaging (PACS)", "Pharmacy Management", "Patient Portal"],
        "maturity_benchmark": "Healthcare organisations typically operate at EA Maturity Level 2-3. EHR consolidation and interoperability are the primary drivers for maturity improvement.",
        "cost_benchmark": "Healthcare IT spend is 3-5% of operating budget. EHR systems represent 30-40% of total IT spend. Legacy systems create significant integration costs.",
        "elimination_guidance": "Clinical systems cannot be eliminated without clinical validation of replacements. Non-clinical administrative apps (HR, finance) have standard elimination criteria. Always flag patient-data-touching apps for enhanced migration scrutiny.",
        "risk_amplifiers": ["Downtime of clinical systems is a patient safety risk — classify as CRITICAL", "Any app storing PHI requires HIPAA-compliant migration path", "Legacy medical device software may have FDA clearance tied to specific software versions"],
        "market_context": "2024-2025: Healthcare sector accelerating cloud EHR migration post-COVID. Cybersecurity attacks on hospitals at all-time high (ransomware). Interoperability mandates (21st Century Cures Act) driving API investment. AI diagnostics gaining FDA clearance rapidly.",
    },

    "Retail & E-commerce": {
        "display": "Retail & E-commerce",
        "sub_sectors": ["E-commerce / D2C", "Grocery & FMCG", "Fashion & Apparel", "Consumer Electronics"],
        "compliance": ["PCI-DSS", "GDPR / CCPA", "Consumer Protection regulations", "VAT/Tax compliance systems"],
        "key_concerns": [
            "Omnichannel customer experience consistency",
            "Real-time inventory visibility across channels",
            "Personalisation and recommendation engines",
            "Supply chain resilience and demand forecasting",
            "Checkout performance (every 100ms of latency = 1% conversion drop)",
            "Returns management and reverse logistics",
        ],
        "tech_trends": [
            "Headless commerce and composable architecture (MACH)",
            "AI-driven personalisation and dynamic pricing",
            "Unified Commerce platforms replacing fragmented POS/ERP",
            "Real-time supply chain visibility platforms",
            "Social commerce and livestream shopping integrations",
        ],
        "critical_app_categories": ["E-commerce Platform", "OMS (Order Management)", "WMS (Warehouse Management)", "POS Systems", "Loyalty & CRM"],
        "maturity_benchmark": "Leading retailers operate at EA Maturity Level 3. Composable/MACH architecture adoption is the key differentiator. Legacy monolithic e-commerce platforms are a major risk.",
        "cost_benchmark": "Retail IT spend is 1-3% of revenue. Platform migration to cloud-native commerce can reduce TCO by 30-50% while improving performance.",
        "elimination_guidance": "Legacy monolithic commerce platforms (Magento 1.x, custom-built POS) are prime elimination candidates. Prioritise anything blocking real-time inventory sync or omnichannel fulfilment.",
        "risk_amplifiers": ["Peak season (Black Friday/Cyber Monday) makes any core platform change high-risk — plan migrations for Q1/Q2", "POS downtime directly impacts revenue — classify as CRITICAL", "Personalisation engines affect conversion rates — migration requires A/B validation"],
        "market_context": "2024-2025: Retail sector under margin pressure from rising logistics costs. AI personalisation and dynamic pricing are table-stakes. Composable commerce (MACH) replacing monolithic platforms. Sustainability reporting requirements increasing for large retailers.",
    },

    "Manufacturing": {
        "display": "Manufacturing & Industrial",
        "sub_sectors": ["Automotive", "Aerospace & Defence", "Consumer Goods", "Industrial Equipment"],
        "compliance": ["ISO 9001", "ISO 27001", "ITAR (Aerospace)", "TISAX (Automotive)", "IEC 62443 (OT Security)", "CMMC (Defence)"],
        "key_concerns": [
            "OT/IT convergence and industrial cybersecurity",
            "Supply chain visibility and multi-tier supplier management",
            "Product lifecycle management (PLM) integration",
            "Predictive maintenance and asset performance",
            "Quality management and traceability",
            "Sustainability and Scope 3 emissions reporting",
        ],
        "tech_trends": [
            "Industrial IoT (IIoT) and smart factory platforms",
            "Digital twin technology for product and plant simulation",
            "Cloud ERP migration (SAP S/4HANA, Oracle Fusion)",
            "AI-powered predictive quality and yield optimisation",
            "5G-enabled factory floor connectivity",
        ],
        "critical_app_categories": ["ERP", "MES (Manufacturing Execution)", "PLM", "SCADA/DCS", "Quality Management (QMS)"],
        "maturity_benchmark": "Manufacturing organisations typically operate at EA Maturity Level 2-3. OT/IT integration and ERP modernisation are primary maturity levers. Many plants have 20+ year old SCADA systems.",
        "cost_benchmark": "Manufacturing IT spend is 1-3% of revenue. Legacy ERP (SAP ECC, Oracle EBS) migration to S/4HANA/Fusion is typically a $10-50M programme for mid-large manufacturers.",
        "elimination_guidance": "OT/SCADA systems require specialised cybersecurity assessment before any change — do NOT apply standard IT elimination criteria. ERP rationalisation to single instance is the highest-value consolidation target.",
        "risk_amplifiers": ["OT/SCADA systems must never be classified as ELIMINATE without OT security assessment", "Plant floor downtime has direct production cost implications", "PLM data is the product IP — migration risk is HIGH"],
        "market_context": "2024-2025: Manufacturing sector accelerating Industry 4.0 adoption. Supply chain disruptions (2020-2023) driving investment in visibility platforms. SAP ECC end-of-life (2027) forcing S/4HANA migration. Sustainability/ESG reporting now mandatory for large manufacturers.",
    },

    "Telecommunications": {
        "display": "Telecommunications",
        "sub_sectors": ["Mobile / MNO", "Fixed Broadband / ISP", "Cable & Media", "Enterprise Telecom / MVNOs"],
        "compliance": ["GDPR", "CALEA (US)", "Lawful Intercept regulations", "Net Neutrality", "Ofcom / FCC regulations", "Number Portability"],
        "key_concerns": [
            "BSS/OSS modernisation (legacy billing and network management)",
            "5G network slicing and monetisation",
            "Network function virtualisation (NFV) and cloud-native network functions",
            "Customer churn prediction and real-time personalisation",
            "Wholesale interconnect and roaming settlement systems",
            "Spectrum management and regulatory compliance",
        ],
        "tech_trends": [
            "Cloud-native BSS/OSS (Amdocs, Ericsson, Nokia)",
            "5G standalone core and network slicing",
            "AI-driven network operations and self-healing networks",
            "ORAN (Open RAN) disaggregation",
            "API monetisation platforms for B2B2X business models",
        ],
        "critical_app_categories": ["BSS (Billing)", "OSS (Network Management)", "CRM", "Network Inventory", "Mediation & Rating"],
        "maturity_benchmark": "Telecom operators typically operate at EA Maturity Level 2-3. BSS/OSS modernisation is the defining challenge — legacy stacks are often 15-20 years old and represent the single largest technical debt.",
        "cost_benchmark": "Telecom IT/network spend is 15-25% of revenue. Legacy BSS/OSS TCO is typically 3-4x cloud-native equivalents. Billing system replacements are $20-100M programmes.",
        "elimination_guidance": "BSS/OSS elimination requires careful data migration planning — subscriber records, billing history, and regulatory data have mandatory retention periods. Network inventory data is foundational — any migration requires full reconciliation.",
        "risk_amplifiers": ["Billing system downtime means revenue loss and regulatory breach", "Number portability databases are CRITICAL infrastructure", "Network inventory inaccuracies cascade into provisioning and field service failures"],
        "market_context": "2024-2025: Telecom sector under intense pressure to monetise 5G investments. BSS/OSS modernisation ($50B+ global market) accelerating. AI-driven network ops (AIOps) mainstream. API economy and platform business models emerging as growth drivers.",
    },

    "Government & Public Sector": {
        "display": "Government & Public Sector",
        "sub_sectors": ["Central / Federal Government", "Local & Municipal", "Defence & Intelligence", "Education"],
        "compliance": ["NIST SP 800-53", "FedRAMP (US)", "Cyber Essentials (UK)", "ISO 27001", "GDPR / Privacy Act", "ATO requirements", "WCAG 2.1 Accessibility"],
        "key_concerns": [
            "Digital transformation of citizen-facing services",
            "Legacy system modernisation (COBOL, mainframe)",
            "Cyber resilience and protection of critical national infrastructure",
            "Data sovereignty and cloud jurisdiction requirements",
            "Procurement compliance and supplier diversity",
            "Interoperability across government agencies",
        ],
        "tech_trends": [
            "Cloud-first / government cloud platforms (GovCloud, Azure Government, G-Cloud)",
            "Low-code / no-code platforms for rapid service delivery",
            "API-based data sharing across departments",
            "AI for fraud detection, benefits eligibility, and demand prediction",
            "Digital identity and single sign-on across services",
        ],
        "critical_app_categories": ["Case Management", "Benefits / Grants Administration", "Tax & Revenue", "Identity & Access Management", "Emergency Services"],
        "maturity_benchmark": "Government agencies typically operate at EA Maturity Level 1-2. Mandatory EA frameworks (TOGAF, FEAF, MODAF) exist but implementation is inconsistent. Legacy debt is proportionally higher than any other sector.",
        "cost_benchmark": "Government IT spend is highly variable. Legacy mainframe costs are often hidden in long-term vendor contracts. Cloud migration can reduce operational costs by 20-40% but requires significant upfront investment.",
        "elimination_guidance": "Government systems often have legislative mandates for data retention (7-25 years). Elimination must include legal review. Citizen-facing services require accessibility compliance (WCAG 2.1) in replacement systems.",
        "risk_amplifiers": ["Citizen-facing systems downtime has public accountability implications", "Tax and benefits systems are political risk — migrations require extensive UAT", "Defence systems have classification requirements — standard cloud migration paths may not apply"],
        "market_context": "2024-2025: Government digital transformation accelerating globally. UK (CDDO), US (Federal Digital Strategy), Australia (APS Digital) all driving cloud-first mandates. AI adoption in government cautious but growing. Cyber threats to critical infrastructure at record levels.",
    },

    "Energy & Utilities": {
        "display": "Energy & Utilities",
        "sub_sectors": ["Oil & Gas", "Electricity Generation & Grid", "Renewables", "Water & Waste"],
        "compliance": ["NERC CIP (North America)", "NIS2 Directive (EU)", "IEC 62351", "ISO 50001", "GDPR", "Environmental reporting (GRI, TCFD)"],
        "key_concerns": [
            "OT/IT convergence and critical infrastructure security",
            "Grid modernisation and smart meter integration",
            "Renewable energy asset management and forecasting",
            "Carbon accounting and ESG/Scope 1-3 reporting",
            "Regulatory price control and asset performance",
            "Energy trading and risk management systems",
        ],
        "tech_trends": [
            "Advanced metering infrastructure (AMI) and smart grid platforms",
            "Digital twin for grid and asset simulation",
            "AI for demand forecasting and renewable dispatch optimisation",
            "Cloud SCADA/ADMS (Advanced Distribution Management Systems)",
            "Battery energy storage management systems (BEMS)",
        ],
        "critical_app_categories": ["SCADA/EMS/DMS", "Asset Management (EAM)", "Energy Trading & Risk (ETRM)", "Billing & Metering", "GIS (Grid/Pipeline Mapping)"],
        "maturity_benchmark": "Energy utilities typically operate at EA Maturity Level 2. OT systems are often 20-30 years old. Smart grid investment is forcing IT/OT integration maturity improvement.",
        "cost_benchmark": "Energy IT spend is 1-3% of revenue for traditional utilities; higher for digital-native energy companies. SCADA replacement programmes are typically $20-100M+ and span 5-10 years.",
        "elimination_guidance": "OT/SCADA systems require IEC 62351 / NERC CIP security assessment before any change. Critical infrastructure designation means government notification may be required for major system changes.",
        "risk_amplifiers": ["OT systems are critical national infrastructure — treat all ELIMINATE recommendations as HIGH RISK requiring specialist OT review", "Grid management downtime has public safety implications", "Energy trading systems have real-time financial exposure"],
        "market_context": "2024-2025: Energy transition driving massive IT investment. Renewables integration requiring grid modernisation. Carbon accounting and ESG reporting now mandatory for large utilities. Cybersecurity attacks on energy infrastructure at record levels post-Ukraine conflict.",
    },

    "Technology": {
        "display": "Technology & Software",
        "sub_sectors": ["SaaS / Cloud Software", "Semiconductor / Hardware", "IT Services / Consulting", "Cybersecurity"],
        "compliance": ["SOC 2 Type II", "ISO 27001", "GDPR / CCPA", "FedRAMP (if serving government)", "NIST CSF"],
        "key_concerns": [
            "Developer productivity and platform engineering",
            "Multi-cloud cost optimisation and FinOps",
            "SaaS portfolio sprawl and shadow IT",
            "Engineering toolchain consolidation",
            "Technical debt reduction and modernisation velocity",
            "AI/ML platform governance and responsible AI",
        ],
        "tech_trends": [
            "Platform engineering and Internal Developer Platforms (IDPs)",
            "FinOps and cloud cost optimisation",
            "AI-assisted software development (GitHub Copilot, etc.)",
            "Observability platforms (OpenTelemetry, Datadog, Grafana)",
            "Zero-trust and DevSecOps integration",
        ],
        "critical_app_categories": ["CI/CD Pipelines", "Cloud Infrastructure (IaC)", "Observability / APM", "Identity & SSO", "Developer Portals"],
        "maturity_benchmark": "Technology companies typically operate at EA Maturity Level 3-4. Higher standards expected — tech firms are EA exemplars. Anything below Level 3 indicates significant internal debt despite external product sophistication.",
        "cost_benchmark": "Technology firms spend 15-30% of revenue on R&D and internal IT. Cloud spend is typically the #1 or #2 cost item. FinOps maturity is a key differentiator.",
        "elimination_guidance": "Engineering tools have high switching costs due to developer workflow changes. Consolidation saves should be weighed against productivity impact. Shadow IT is pervasive — discovery and rationalisation is a high-value exercise.",
        "risk_amplifiers": ["CI/CD pipeline downtime stops engineering delivery — CRITICAL", "Observability gaps create incident response blind spots", "IAM system issues affect all downstream services"],
        "market_context": "2024-2025: Technology sector under cost pressure post-2022 correction. AI tooling investment highest priority. FinOps maturity becoming competitive necessity. Platform engineering trend replacing DevOps silos. SOC 2 now table-stakes for enterprise sales.",
    },

    "Professional Services": {
        "display": "Professional Services",
        "sub_sectors": ["Consulting & Advisory", "Legal", "Accounting & Audit", "Architecture & Engineering"],
        "compliance": ["GDPR / CCPA", "SOC 2", "ISO 27001", "Client confidentiality obligations", "Sector-specific bars (legal, accounting)"],
        "key_concerns": [
            "Knowledge management and IP protection",
            "Billable hour tracking and project profitability",
            "Client data segregation and confidentiality",
            "Remote workforce collaboration and productivity",
            "AI augmentation of professional work",
            "Talent attraction and retention tools",
        ],
        "tech_trends": [
            "AI-assisted document review, contract analysis, and research",
            "Modern PSA (Professional Services Automation) platforms",
            "Unified collaboration (Teams, Slack) consolidation",
            "Cloud document management (SharePoint, iManage for legal)",
            "Business intelligence for project portfolio management",
        ],
        "critical_app_categories": ["PSA (Project Management & Billing)", "CRM / Opportunity Management", "Document Management (DMS)", "Collaboration (Email, Video)", "ERP / Finance"],
        "maturity_benchmark": "Professional services firms typically operate at EA Maturity Level 2-3. IT is a cost centre with high SaaS sprawl. Knowledge management quality is the key differentiator.",
        "cost_benchmark": "Professional services IT spend is 3-6% of revenue. SaaS sprawl is pervasive — average firm has 3-5x more SaaS tools than needed. Consolidation typically yields 20-35% IT cost reduction.",
        "elimination_guidance": "High SaaS sprawl — prioritise duplicate collaboration, project management, and analytics tools. Client data migration requires strict data handling procedures and potentially client notification.",
        "risk_amplifiers": ["Billing system downtime affects revenue recognition — HIGH priority", "Client confidentiality breach is an existential risk — flag any app touching client data", "Knowledge loss during tool migration can impact project delivery"],
        "market_context": "2024-2025: Professional services sector being disrupted by AI (legal tech, accounting automation, AI consulting). SaaS rationalisation top of mind due to cost pressure. Microsoft 365 / Google Workspace consolidation mainstream. Generative AI for knowledge work accelerating.",
    },

    "Media & Entertainment": {
        "display": "Media & Entertainment",
        "sub_sectors": ["Streaming & OTT", "Broadcasting", "Gaming", "Publishing & News"],
        "compliance": ["GDPR / CCPA", "COPPA (children's content)", "Content licensing regulations", "OFCOM / FCC broadcast rules"],
        "key_concerns": [
            "Content delivery at global scale (CDN performance)",
            "Streaming platform reliability and QoE",
            "Rights management and content licensing systems",
            "Personalisation and recommendation algorithms",
            "Advertising technology (AdTech) and programmatic",
            "Content production workflow digitisation",
        ],
        "tech_trends": [
            "Cloud-native media supply chains (AWS MediaServices, Azure Media)",
            "AI content recommendation and personalisation",
            "IP-based production workflows replacing SDI",
            "Programmatic advertising and first-party data strategies",
            "AI-generated content tools and governance",
        ],
        "critical_app_categories": ["Content Management (CMS/MAM)", "OTT/Streaming Platform", "Rights Management", "AdTech / Ad Server", "Production Workflow"],
        "maturity_benchmark": "Media companies range from Level 1 (legacy broadcasters) to Level 4 (digital-native streaming). Legacy broadcast infrastructure is the primary technical debt challenge.",
        "cost_benchmark": "Media IT spend is 3-8% of revenue. Cloud content delivery is now the dominant cost model. Legacy tape and SDI infrastructure has high maintenance costs with declining value.",
        "elimination_guidance": "Legacy tape archives require content migration before any system elimination. Rights management systems contain licensing obligations — legal review required before decommission.",
        "risk_amplifiers": ["Streaming platform downtime is public and reputationally damaging", "Rights management errors can result in licensing violations and lawsuits", "Content loss during migration is irreversible — treat as CRITICAL risk"],
        "market_context": "2024-2025: Streaming sector consolidation and cost reduction (Netflix, Disney+ profitability focus). AI content production tools rapidly maturing. Advertising market soft but programmatic growing. Gaming sector integrating AI for content generation and anti-cheat.",
    },

    "Other": {
        "display": "Other / General",
        "sub_sectors": [],
        "compliance": ["GDPR", "ISO 27001", "SOC 2"],
        "key_concerns": [
            "Reducing technical debt and legacy system costs",
            "Improving IT agility and time-to-market",
            "Cloud adoption and cost optimisation",
            "Cybersecurity posture improvement",
            "Data quality and analytics capability",
        ],
        "tech_trends": [
            "Cloud migration and hybrid cloud adoption",
            "SaaS consolidation and spend optimisation",
            "AI/ML adoption for operational efficiency",
            "Zero-trust security architecture",
            "Data mesh and modern analytics platforms",
        ],
        "critical_app_categories": ["ERP", "CRM", "Identity & Access Management", "Core Business Applications", "Analytics"],
        "maturity_benchmark": "Industry average EA maturity is Level 2. Organisations at Level 3+ demonstrate systematic governance and measurable business outcomes from EA investment.",
        "cost_benchmark": "Average IT spend is 3-6% of revenue. Cloud migration typically yields 20-35% infrastructure cost reduction over 3 years.",
        "elimination_guidance": "Focus elimination efforts on duplicate SaaS tools, shadow IT, and applications with fewer than 10 active users. Prioritise cost impact and integration complexity.",
        "risk_amplifiers": ["Any app with no identified owner is a security and continuity risk", "Applications with no documented APIs are migration blockers"],
        "market_context": "2024-2025: Organisations across all sectors are rationalising IT portfolios post-pandemic spending surge. AI adoption accelerating. Cloud cost optimisation (FinOps) a top priority for CIOs.",
    },
}


def get_industry_context(industry: str, sub_sector: str = None) -> str:
    """
    Returns a formatted industry context block to be appended to any agent system prompt.
    """
    ctx = INDUSTRY_CONTEXT.get(industry) or INDUSTRY_CONTEXT["Other"]
    label = f"{industry} — {sub_sector}" if sub_sector else industry

    lines = [
        f"\n\n{'='*60}",
        f"INDUSTRY CONTEXT: {label}",
        f"{'='*60}",
        f"\nMarket Context (current, 2024-2025):\n{ctx['market_context']}",
        f"\nKey Industry Concerns:",
        *[f"  • {c}" for c in ctx["key_concerns"]],
        f"\nCompliance & Regulatory Requirements: {', '.join(ctx['compliance'])}",
        f"\nCritical Application Categories (treat downtime as HIGH/CRITICAL):\n  {', '.join(ctx['critical_app_categories'])}",
        f"\nTechnology Trends Shaping This Industry:",
        *[f"  • {t}" for t in ctx["tech_trends"]],
        f"\nMaturity Benchmark: {ctx['maturity_benchmark']}",
        f"\nCost Benchmark: {ctx['cost_benchmark']}",
        f"\nElimination / Migration Guidance: {ctx['elimination_guidance']}",
        f"\nIndustry Risk Amplifiers:",
        *[f"  ⚠ {r}" for r in ctx["risk_amplifiers"]],
        f"\n{'='*60}",
        f"INSTRUCTION: Apply the above industry context to ALL analysis, scoring,",
        f"recommendations, and report language. Use industry-standard terminology.",
        f"Reference specific compliance frameworks and market trends where relevant.",
        f"Benchmark findings against industry peers, not generic IT standards.",
        f"{'='*60}\n",
    ]
    return "\n".join(lines)
